FROM amazoncorretto:8
MAINTAINER emmanuel-f5
COPY /home/emmanuel/Escritorio/Portfolio/Portfolio_EmmanuelFlores/Portfolio_EmmanuelFlores/BackEnd/target/eflores-0.0.1-SNAPSHOT.jar eflores-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/eflores-0.0.1-SNAPSHOT.jar"]
